services:

  robot-client:
    build:
      context: ./api-call-handler/client-dummy
    container_name: robot-client
    ports:
      - "8080:8080"
    network_mode: "host" 
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: unless-stopped

  wms-server:
    build:
      context: ./api-call-handler/wms-server
    container_name: wms-server
    ports:
      - "8081:8081"
    network_mode: "host" 
    restart: unless-stopped

  hmi:
    build:
      context: ./hmi
    container_name: hmi
    ports:
      - "8082:8082"
    network_mode: "host" 
    depends_on:
      - wms-server
      - robot-client
    restart: unless-stopped

  ros2-nodes:
    build:
      context: ./ros2-nodes
    container_name: ros2-nodes
    network_mode: "host"
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: unless-stopped

networks:
  robocell-net:
    driver: bridge